### ISSUE TITLE
TMDbWrapper project missing SeasonSummary.cs file

### ISSUE THREAD

**Issue by nCubed** [Fishes/TMDbWrapper#3]
Pulled the latest this afternoon and found the SeasonSummary.cs file missing from the TmdbWrapper.csproj project. This breaks the build where TVSeries and TheMovieDbTv have dependencies on SeasonSummary.

**Comment by Fishes** [comment]
Thanks, for notifying me.


Later today I will fix this as soon as I am able to.








From: kindler chase
Sent: ‎Sunday‎, ‎March‎ ‎8‎, ‎2015 ‎8‎:‎15‎ ‎PM
To: Fishes/TMDbWrapper





Pulled the latest this afternoon and found the SeasonSummary.cs file missing from the TmdbWrapper.csproj project. This breaks the build where TVSeries and TheMovieDbTv have dependencies on SeasonSummary.

**Comment by Fishes** [comment]
I have included the missing file.
